name: Tests

on:
  push:
    branches:
      - '**'
      - '!main'


jobs:
  publish:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Get number of tags
        id: get-tags
        run: |-
          TAG_COUNT=`git tag | wc -l`
          echo "counted ${TAG_COUNT} tags";
          echo "::set-output name=count::${TAG_COUNT}";
      
      - name: "Build Changelog"
        if: steps.get-tags.outputs.count > 1
        id: changelog
        uses: Requarks/changelog-action@v1
