name: Claim Command Reaction
on:
  repository_dispatch:
    types: [claim-command]
jobs:
  claimCommandReaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.PAT }}
          assignees: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}
          number: ${{ github.event.client_payload.slash_command.args.named.issue_number }}
