name: Claim Command Reaction
on:
  repository_dispatch:
    types: [claim-command]
jobs:
  claimCommandReaction:
    runs-on: ubuntu-latest
    steps:
      - name: Output command and arguments
        run: |
          echo ${{ github.event.client_payload.slash_command }}
          echo ${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}
