on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic version number to use in release: ^[0-9]+.[0-9]+.[0-9]+(-[a-zA-Z0-9.-]+){0,1}$'
        required: true
      prerelease:
        description: 'This release is a pre-release'
        required: true
        type: boolean
        default: false

jobs:
  prepare:
    runs-on: ubuntu-latest

    outputs:
      branch: ${{ steps.release-branch-name.outputs.name }}

    steps:
      - name: Determine release branch name
        id: release-branch-name
        run: |-
          BRANCH=${GITHUB_REF#refs/heads/}
          if [[ ${BRANCH} == stable/* ]] || [[ ${PRERELEASE} == true ]]; then 
            # use the current branch name (maintenance release or alpha/rc)
            echo "::set-output name=name::${BRANCH}";
          elif [[ ${BRANCH} == "main" ]]; then
            # this is a release, derive a new maintenance branch name
            [[ $VERSION_INPUT =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)(-[a-zA-Z0-9.-]+){0,1}$ ]]
            echo "::set-output name=name::stable/${BASH_REMATCH[1]}.${BASH_REMATCH[2]}";
          else
            # unsupported branch
            echo "Unsupported release branch ${BRANCH}. Please release from main branch or a stable/* branch" && exit 1;
          fi
        env:
          VERSION_INPUT: ${{ github.event.inputs.version }}
          GITHUB_REF: ${{ github.ref }}
          PRERELEASE: ${{ github.event.inputs.prerelease }}
      - name: Output branch name
        run: |-
          echo "branch: ${{ steps.release-branch-name.outputs.name }}"

